name: im_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  firebase_core: latest
  firebase_auth: latest
  cloud_firestore: latest
  firebase_messaging: latest
  flutter_local_notifications: latest
  image_picker: latest
  file_picker: latest
  flutter_chat_ui: latest
  flutter_chat_types: latest
  encrypt: ^5.0.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
