name: im_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.4.0
  firebase_messaging: ^14.0.0
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.5
  file_picker: ^5.0.0
  flutter_chat_ui: ^2.0.0
  flutter_chat_types: ^3.1.0
  encrypt: ^5.0.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
