name: im_app
description: A new Flutter IM app.
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase 依赖（适配 Dart 2.16.0 的版本）
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1

  # 状态管理（兼容旧版）
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4  # 降级 lint 规则

flutter:
  uses-material-design: true
