name: Flutter Enterprise CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/screenshots/**'
  pull_request:
    branches: [ master ]

env:
  FLUTTER_VERSION: '3.19.5'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true
        cache-key: flutter-ubuntu-${{ env.FLUTTER_VERSION }}
        cache-path: ${{ github.workspace }}/.pub-cache

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Tests
      run: flutter test --coverage

    - name: Build Artifacts
      run: |
        flutter build apk --release --split-per-abi
        flutter build appbundle --release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build-${{ github.run_number }}
        path: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/bundle/release/*.aab

  ios-build:
    name: iOS Build
    needs: android-build
    runs-on: macos-14
    timeout-minutes: 45

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true
        cache-key: flutter-macos-${{ env.FLUTTER_VERSION }}
        cache-path: ${{ github.workspace }}/.pub-cache

    - name: Install Pods
      run: |
        cd ios && pod install --repo-update

    - name: Build IPA
      run: flutter build ipa --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-${{ github.run_number }}
        path: build/ios/ipa/*.ipa
