name: Flutter CI/CD

on:
  push:
    branches:
      - master  # 保持使用 master 分支
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master  # PR 目标分支保持 master

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        flutter-version: ['3.16.9']
        include:
          - flutter-version: '3.16.9'
            channel: stable

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}  # 明确指定使用触发分支

    # ... 其他步骤保持不变 ...

  build-ios:
    name: iOS Build
    needs: test-and-build
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: master  # 明确检出 master 分支
        fetch-depth: 0  # 获取完整提交历史

    # ... 其他步骤保持不变 ...
