name: Flutter CI/CD

on:
  push:
    branches:
      - master  # 修正分支名称（原错误拼写 naster → master）
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - master

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: master  # 明确指定分支

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'
        channel: stable

    - name: Build & Test
      run: |
        flutter pub get
        flutter analyze
        flutter test
        flutter build apk --release --split-per-abi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: build/app/outputs/flutter-apk/*.apk

  ios-build:
    name: iOS Build
    needs: android-build
    runs-on: macos-14
    timeout-minutes: 40

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: master  # 同步分支配置

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    - name: Build IPA
      run: |
        flutter pub get
        cd ios && pod install
        flutter build ipa --release

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-release
        path: build/ios/ipa/*.ipa
