name: Flutter CI/CD

on:
  push:
    branches:
      - main  # 推荐使用 main 作为默认分支
    paths-ignore:  # 忽略非代码变更
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        flutter-version: ['3.16.9']  # 2024年最新稳定版
        include:
          - flutter-version: '3.16.9'
            channel: stable

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}
        channel: ${{ matrix.channel }}
        cache: true
        cache-key: flutter-${{ matrix.flutter-version }}
        cache-path: ${{ github.workspace }}/.pub-cache

    - name: Install Dependencies
      run: |
        flutter pub get
        flutter precache --android --ios

    - name: Analyze Code
      run: flutter analyze --no-pub

    - name: Run Tests
      run: flutter test --coverage --test-randomize-ordering-seed random

    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        files: coverage/lcov.info

    - name: Build Android APK
      run: |
        flutter build apk --release --split-per-abi
        ls -la build/app/outputs/flutter-apk/

    - name: Upload Android Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apks
        path: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/bundle/release/app-release.aab
        retention-days: 7

  build-ios:
    name: iOS Build
    needs: test-and-build
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: stable

    - name: Install Dependencies
      run: |
        flutter pub get
        cd ios && pod install --repo-update

    - name: Build iOS IPA
      run: |
        flutter build ipa --release --export-options-plist=ExportOptions.plist
        ls -la build/ios/ipa/

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: build/ios/ipa/*.ipa
        retention-days: 7
